### ISSUE TITLE
Inconsistent column order.

### ISSUE THREAD

**Issue by jorwoods** [chdoig/pytexas2015-ml#1]
Noticed an issue where the columns end up out of order when compared to what they started with. With each run, list(expand_vectorizer.vocabulary_.keys()) produces a somewhat different order, but the order of the vectorizer output is consistent with the order of the items of the input list. I've attached a screenshot to show the difference.
![word order](https://cloud.githubusercontent.com/assets/13803242/10119068/01142600-6451-11e5-8f2f-0cc3edb57f74.png)

**Comment by chdoig** [comment]
Closed in #2
